### PR TITLE
remove flush socket from server socket 'down' handling

### PR DESCRIPTION
**Pull request by tsloughter**
Not sure what to do if the data on the socket is not an error or normal close. Should we continue to receive until it is either empty or gives the error or normal close response?

@seancribbs @evanmcc ?

### CODE REVIEW

**Comment by seancribbs** [comment]
Agreeing with @evanmcc in Slack here: we probably don't need to do anything special when the connection exits other than to stop. Maybe if it's an abnormal exit we should propagate that?

**Comment by tsloughter** [comment]
Sure, I'd agree. But how do we know it is abnormal without this loop? I'm fine either way.

**Comment by evanmcc** [comment]
looks fine to me, I'm too hazy on where this could happen to know how important it is.

**Comment by cmeiklejohn** [comment]
So, it's not necessary to flush the socket?

**Comment by seancribbs** [comment]
@cmeiklejohn I don't think so, it seems that the monitor is only relevant if it's not the controlling process, because `active` mode messages will be delivered before the `DOWN` signal:

```
12> {ok, Port} = gen_tcp:connect({216,58,217,174}, 443, [{active, true}]), monitor(port, Port).
#Ref<0.0.7.194>
13> gen_tcp:send(Port, "GET / HTTP/1.1 \n\n").
ok
14> flush().
Shell got {tcp_closed,#Port<0.474>}
Shell got {'DOWN',#Ref<0.0.7.194>,port,#Port<0.474>,normal}
ok
```

There might still be a race when we have upgraded to TLS, because the underlying TCP socket might exit before the intermediary stood up by the `ssl` app sends the `ssl_closed` message.

**Comment by cmeiklejohn** [comment]
Good to merge?

**Comment by tsloughter** [comment]
@cmeiklejohn this should be good to merge.

**Pull request merged**
