### PR TITLE
various cleanup tasks to remove unneeded deps

### PR DESCRIPTION
**Pull request by tsloughter**
Since the min otp version in the rebar.config is 19 the `_compat` libraries could be removed.

The parse transform dep for stacktraces was replaced with a macro.

Test deps were moved to the test profile along with the release definition which used eredis. I updated the makefile and dockerfile but may have missed other places this was referenced.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Am I correct in understanding that this drops support for 19.3 completely?  (I'm a bit concerned, because while I know it's not a supported release, there's a few Riak related projects that use this and very much are still running on 19.3.)

**Comment by tsloughter** [comment]
Hm, which change do you think removes support for 19.3? Pretty sure the `_compat` libs were only fore pre-18 support and I added the macro so that stacktrace stuff still works on older releases.

**Comment by cmeiklejohn** [comment]
Oh, I was under the impression that 19.3 support required the compat libraries.  Maybe you can update this PR to modify the travis file to include 19.3 as part of the build again?

**Comment by tsloughter** [comment]
Ah ok, yea, I'll add that.

**Comment by tsloughter** [comment]
@cmeiklejohn so it doesn't build on 19.3 because of the use of `~tw` in `partisan_gen_fsm.erl`:

```
src/partisan_gen_fsm.erl:512: format string invalid (invalid control ~tw)
```

**Comment by cmeiklejohn** [comment]
Ah, this must be because we took this directly from gen_server in OTP 20.3.    What do you think?

**Comment by tsloughter** [comment]
I can either reremove 19.3 and udpate rebar.config to have min version of 20 or change the `~tw` to ~w`.

**Comment by cmeiklejohn** [comment]
I suppose just fix the format string.

**Comment by tsloughter** [comment]
K, done, lets see if it passes now.

**Comment by cmeiklejohn** [comment]
Thanks.

**Comment by cmeiklejohn** [comment]
looks like your branch needs an empty code_change callback in the hbbft worker module -- can you add that to your branch?

**Comment by tsloughter** [comment]
Ah, yup, will do.

**Comment by cmeiklejohn** [comment]
cherry-picked commits into master manually.

**Pull request merged**
