### PR TITLE
API Changes

### PR DESCRIPTION
**Pull request by vitorenesduarte**
- [x] Remove `decode/1` from manager behaviour
- [x] Add `myself/0` to manager behaviour

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Decode is needed by code in sprinter and lasp, I'm not sure you can just remove it.

**Comment by cmeiklejohn** [comment]
The membership becomes not mergeable (in the default peer service manager, it's a CRDT) if you remove decode -- that's primarily why it was added.

**Comment by vitorenesduarte** [comment]
I saw `decode` being used in new membership event callbacks.
If we pass to the callback the already decoded membership, we don't need `decode`.

**Comment by vitorenesduarte** [comment]
See #30

**Pull request closed without merging**
