### PR TITLE
Change persist epoch

### PR DESCRIPTION
**Pull request by getong**
I recheck the code for many times, and find that, the manager process dies and restarts, the connections are all lost, but the active and the passive are still remained. So the other network close, the active will not be deleted and not correct.The solution I think is only persist the epoch. 
The xbot module does have the same problem, I don’t know the solution is correct or not,  if the pr is merged, I will make a new pr to the xbot module.
Feedback is needed.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
What's the status of this PR?

**Comment by getong** [comment]
The pr is completed.

**Comment by cmeiklejohn** [comment]
Is there an associated change for the xbot backend too?  It looks like it also needs this same change.

**Comment by getong** [comment]
Yes, I will do it today.

**Pull request merged**
