### PR TITLE
Spanning trees [in the app]

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@lrascao Please review.

**Comment by cmeiklejohn** [comment]
@lrascao Please review.

**Comment by lrascao** [comment]
I'm a bit confused by this, i always thought of plumtree as being a client of a membership service (as is partisan) to be used for broadcast, why is partisan now also handling broadcast instead of just worrying about managing membership?

**Comment by cmeiklejohn** [comment]
It's not worrying about broadcast, it's worrying about unicast, more.  If I want the ability for any node to send to any other node in the cluster using the HyParView topology, I need to have nodes forward messages on behalf of other nodes.

Two problems arise from this, messages can ping pong between a set of nodes if the network is being reconfigured, which can easily happen in HyParView. This prevents termination of the algorithm (which can be alleviated through the use of a TTL, but with no increased probability of message delivery.)

Instead, I'm using plumtree for only spanning tree membership but using broadcast messages to construct a tree: by doing this I can always send down the out links of a node, and I don't have to worry about termination.  This just means that during network churn, a message may be lost, but the probability of delivery stays higher than the previous aporoach.

**Comment by cmeiklejohn** [comment]
Plumtree at this point is really only like two more modules and so highly dependent on partisan, that I think brining the tree computation directly makes sense.

**Comment by cmeiklejohn** [comment]
Plumtree at this point is really only like two more modules and so highly dependent on partisan, that I think brining the tree computation directly makes sense.

**Comment by cmeiklejohn** [comment]
Would it be preferable if I duplicated the modules in here instead?  Might be, so then users of plumtree with another peer service can use that?

**Pull request merged**
