### PR TITLE
Use connection cache also on hyparview manager

### PR DESCRIPTION
**Pull request by lrascao**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
It looks like this is failing?

**Comment by lrascao** [comment]
yeah, just realized this won't work until #58 is merged, guess it'll have to wait

**Comment by cmeiklejohn** [comment]
I'll try to take care of these outstanding PRs tonight.

**Comment by cmeiklejohn** [comment]
Please rebase on master and we'll get this merged.

**Pull request closed without merging**
