### PR TITLE
bump acceptor pool to 1.0.0

### PR DESCRIPTION
**Pull request by benoitc**
bring compatibility to erlang 21 (and some fixes

### CODE REVIEW

**Comment by benoitc** [comment]
i'm not reproducing the issue locally, maybe an issue with travis?

```
± |acceptor_pool-1.0.0 U:1 ✗| → rebar3 ct
===> Verifying dependencies...
===> Compiling partisan
===> Running Common Test suites...
%%% partisan_SUITE: ..................................
All 34 tests passed.
```


> note: i'm using latest rebar3 and openssl installed from homebrew on my mac.

```
rebar3 --version
rebar 3.8.0 on Erlang/OTP 21 Erts 10.2.1
```

**Comment by cmeiklejohn** [comment]
Travis is building with Erlang 20.3.

**Comment by benoitc** [comment]
@cmeiklejohn It shouldn't make any change since the update doesn't break the compatibility with erlang 20. It seems like a timing issue in tests not something related to the acceptor pool.

**Comment by benoitc** [comment]
@cmeiklejohn maybe you can relaunch the test inside travis to see if it's pass.

**Comment by benoitc** [comment]
running on travis from my account I get a different error: 
https://travis-ci.org/benoitc/partisan/jobs/482557319

maybe you know what’s going on? any hint is welcome

**Comment by cmeiklejohn** [comment]
There's something wrong with this PR that's causing the execution of the system to be different somehow.  Which, is causing these test failures.  Anyway, it would be better to target this against the rename-backend branch.

**Comment by benoitc** [comment]
@cmeiklejohn i think @tsloughter and I found something related to a recent change in acceptor_pool. I will update it asap with a working one. Change is pretty isolated anyway so it should be straight forward to re-apply it on the `rename-branch`

 I'm fine to have it integrated later but can you keep  the PR open so we can make sure the tests pass?

**Comment by benoitc** [comment]
it's fixed with last commit.

**Comment by cmeiklejohn** [comment]
Do we know if this test failure is a genuine failure or a new race condition introduced by the change?

**Comment by benoitc** [comment]
@cmeiklejohn I can reproduce it without the change from time to time. Probably a race condition during the test setup. We noticed however that you're using the same pool for each listeners. I have a coming fix for it :)

**Comment by cmeiklejohn** [comment]
Is this good to merge @benoitc ?

**Comment by benoitc** [comment]
@cmeiklejohn yes,  this change only bump to latest stable version of acceptor_pool.

**Pull request merged**
