### PR TITLE
Ensure peer port config var on system allocated port

### PR DESCRIPTION
**Pull request by lrascao**
If a zero value is configured for the peer port variable
ensure that, after bind, the final system allocated port
number is obtained and set in the configuration.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
What happens if a node has multiple random listen addrs?  Obviously, one change is going to be lost here.

**Comment by lrascao** [comment]
damn it, you're right, i'm still thinking only on the old way

**Comment by lrascao** [comment]
maybe update the listen address port that matches the listening ip address?

**Comment by cmeiklejohn** [comment]
Yeah, I would basically modify the listen_addrs with the assigned port.

**Comment by lrascao** [comment]
@cmeiklejohn please take another look when you get a chance, i'm now updating `listen_addrs` as well as `peer_port` config vars

**Pull request merged**
