### PR TITLE
Use the resolution of node name.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Resolve the node name and use the node name for the default IP address, instead of 127.0.0.1.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@tsloughter What do you think of this change?

**Comment by tsloughter** [comment]
Can you have it only do this if the application env variable isn't set?

**Comment by cmeiklejohn** [comment]
I just pushed a change that should do that.

**Comment by cmeiklejohn** [comment]
I'm going to merge this, let me know if you have any objections with it.

**Pull request merged**
