### PR TITLE
Get port from the environment.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by tsloughter** [comment]
Why this instead of just using the configs (which can also have os vars when run from a relx release)?

These (reading in from the os env directly in the code) always seem to end up causing problems with getting understandable results when setting config values.

**Comment by cmeiklejohn** [comment]
I don't plan to merge this, but I need it for experiments for a paper deadline in 7 days.  When I'm running 4000 node experiments in Amazon, I can't really build 4000 different releases.

**Comment by tsloughter** [comment]
Ah, ok.

But also, no, you don't need to build a release with the port number set. The releases can be configured with environment variables. Like in sys.config:

```
{partisan, [{peer_port, "${PEER_PORT}"}]}
```

Or in vm.args to get an integer:

```
-partisan peer_port ${PEER_PORT}
```

**Comment by cmeiklejohn** [comment]
But, I can't put that into the default vm.args though, right?  I'll run into the same issues as doing it in the environment?

**Comment by cmeiklejohn** [comment]
Can you help me figure out how to do this so it's just a setting for the exp-stage build?  That's all I need.

**Comment by tsloughter** [comment]
What is the "exp-stage build"? And you could put it in the default vm.args, or in a `prod` profile `vm.args`. But if this current patch works for you then it doesn't really matter if it isn't going into master.

**Comment by cmeiklejohn** [comment]
I'm referring to the staging release build in Lasp that's triggered by the `make exp-stage` target.  Can you point me to how I could adapt just that build to use it's own `vm.args` file with this change so I don't need to rely on that branch where I've used the port from the environment (in fact, this branch)?  Then, I can close that.

**Pull request closed without merging**
