### PR TITLE
Do not gossip membership in client server

### PR DESCRIPTION
**Pull request by vitorenesduarte**
#33

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
I feel like we tried to make this change before and we broke something -- do you remember what it was?

**Comment by vitorenesduarte** [comment]
Not 100% sure, but I think that when I tried to remove `decode/1` from the manager API.

**Comment by cmeiklejohn** [comment]
Did you test this with any of the Lasp experiments?  I would be good to do that before we merge it.

**Comment by vitorenesduarte** [comment]
No. Once the cluster is free, I can do some runs with this branch.

**Comment by cmeiklejohn** [comment]
Sounds good.

**Comment by zeeshanlakhani** [comment]
👍 great to see how this works after the cluster-run!

**Comment by cmeiklejohn** [comment]
@vitorenesduarte Please review my changes from the merge.

**Comment by cmeiklejohn** [comment]
I'm confused -- this code still appears to be persisting the changes to disk, but then it doesn't delete the state when the node leaves.  Is that intentional or is there motivation behind this change?

**Comment by vitorenesduarte** [comment]
No motivation. I don't know all the components, so I might have done something wrong.

**Comment by cmeiklejohn** [comment]
I think for this to be mergeable, we need to restore the code about deleting the state.

**Pull request merged**
