### PR TITLE
Xbot integration

### PR DESCRIPTION
**Pull request by brunosantiagovazquez**
New service based on hyparview where the xbot development was integrated.
Tests done based on hyparview ones too but using the new developed service (into partisan_SUITE.erl).

The new service is called partisan_hyparview_xbot_peer_service_manager.erl
In partisan.hrl was included some params and the xbot interval into node_spec definition for XBOT support. 
In partisan_peer_service_manager.erl was included the initialization of the xbot interval.

### CODE REVIEW

**Comment by benoitc** [comment]
xbot?

**Comment by tsloughter** [comment]
Came here to ask the same question as @benoitc :)

**Comment by cmeiklejohn** [comment]
Surprises, gents!  Don't spoil them.

**Comment by cmeiklejohn** [comment]
@brunosantiagovazquez is there anything we can do to resolve these type specification errors?  I think it's because the node spec is no longer valid.

**Pull request merged**
