### PR TITLE
[WIP] Prototype libp2p transport.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@Vagabond @madninja

What I have here should swap out the `gen_tcp` backend at runtime, in favor of sending messages over the `libp2p` backend.  I've done a few things (keeping in mind that Partisan connections are unidirectional only, at the moment.)

a.) Each client connection should open a stream using the `dial` API for a given target node, and route all connections using that stream via `libp2p_connection:send` function.
b.) On initialization, the server connection should listen on the appropriate IP/port combination using the `libp2p_swarm:listen` function.

Therefore, I think the only piece that's missing is how the server receives messages sent on the stream -- however, given the lack of documentation in the `libp2p` API, I can't figure out how or where that's supposed to be done.  

Do I call `add_stream_handler` on the server side and supply a module callback that will be used to receive these messages?  It's unclear what I do on the side I've connected to once I open a stream...

**Comment by madninja** [comment]
@cmeiklejohn Yeah, libp2p is very much a wip right now. Documentation is coming as the api settles down. 

I see you're figuring out the low level stream handler API. We have a higher level generic framed stream server and client callback based approach that reduces much of the boiler plate you would otherwise have to use. I recommend you take a look at that. 

An example of an echo stream server handler: 

https://github.com/helium/erlang-libp2p/blob/master/test/echo_stream.erl

**Comment by cmeiklejohn** [comment]
I got it working; turns out, I found most of what I needed in the framed stream.

**Comment by madninja** [comment]
Cool beans.. having to further the spread of the use of inert is.. ugh..

**Comment by cmeiklejohn** [comment]
Now, you should just be able to toggle `partisan_config:set(transport, libp2p)` and run Plumtree, Lasp, and Partisan over libp2p.

**Pull request closed without merging**
