### PR TITLE
Random walk to a single node.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Correct an inconsistency in the paper where the random walk is performed
to all nodes, when it should be a random walk to a single node.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@junghunyoo Can you look at this?

**Comment by cmeiklejohn** [comment]
So, it appears that changing the incorrect random walk code in this implementation to the paper's single random walk is now causing the test suite to fail because graph connectivity can not me established.  Thoughts?

**Comment by junghunyoo** [comment]
The change looks fine. I thought that the FORWARDJOIN message needs to be sent to all nodes in the active view except itself (in paper: The contact node c will then send to all other nodes in its active view a FORWARDJOIN request containing the new node identifier). If we send only a single random walk message, I think it would be very difficult to have the connected graph.

**Comment by lrascao** [comment]
I think the original implementation is already consistent with the paper, as @junghunyoo mentioned on `JOIN` the connect node sends `FORWARD JOIN` to the active view. Only when processing `FORWARD JOIN` is a random node from the active view selected.

**Comment by cmeiklejohn** [comment]
I don't think I agree; the paper seems to indicate one node will be selected -- which is in line with the text which assumes a single 'random walk' being performed.  However, the cluster's scalability is reduced when we no longer random walk once per peer.

**Comment by lrascao** [comment]
That's interesting, my interpretation of the paper jibes with the code that was implemented, i'm referring to the section that goes like this (page 7):
````
The contact node c will then send to all other nodes in its active view a ForwardJoin request
containing the new node identifier. The ForwardJoin request will be propagated in the overlay
using a random walk.
````
but probably i'm missing something, thoughts?

**Comment by cmeiklejohn** [comment]
I think the problem here is that the algorithm specification doesn't match the text.  Given that the algorithm no longer ensures a single connected component with high probability without this change, let's assume the text is correct.

**Comment by cmeiklejohn** [comment]
I'm going to close the PR for now.

**Pull request closed without merging**
