### PR TITLE
the sleep time should be random number

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Any thoughts on the failures here?

**Comment by cmeiklejohn** [comment]
Did you commit your changes?  It's still failing....

**Comment by cmeiklejohn** [comment]
Can you update all of this in the commit?

**Comment by getong** [comment]
I changed the test code, but I reset it. I just think the test code should not be changed.

**Comment by cmeiklejohn** [comment]
Obsoleted by https://github.com/lasp-lang/partisan/pull/182

**Pull request closed without merging**
