### PR TITLE
Ensure the config overrides the default setting.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by tsloughter** [comment]
This looks like it will always result in the listen addrs using the default port instead of the configured one?

**Comment by lrascao** [comment]
yeah, i was just about to mention that as well

**Comment by cmeiklejohn** [comment]
Bah, this backwards compatibility shit is awful.  I want to deprecate IP/PORT completely in favor of listen addrs, but I don't want to break everything.

**Comment by cmeiklejohn** [comment]
Right now, it's skipping the listen_addrs specified in the configuration completely.

**Comment by lrascao** [comment]
i suggest we tag this github repo (with gitflow for example) instead of just relying on hex.
This way we could rely on a 1.0.0 support branch while you go on developing new stuff on some other branch (like `develop`)

**Comment by cmeiklejohn** [comment]
Does this change look more appropriate?

**Pull request merged**
