### PR TITLE
fix decode result

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by lrascao** [comment]
weird that dialyzer doesn't catch this

**Comment by getong** [comment]
I think, there are no data in the starting.

**Comment by getong** [comment]
This is a runtime error. I don't think dialyzer will catch it.

**Comment by lrascao** [comment]
ah, `binary_to_term` is spec'ed like this:
   `binary_to_term(Binary) -> term()`

so that's why

**Comment by getong** [comment]
I don't use dialyzer, but it seems that it worth learning to use.

**Comment by lrascao** [comment]
definitely, saved my ass a bunch of times

**Comment by getong** [comment]
Thanks, I will learn it.

**Pull request merged**
